name: ARMv8 Docker BuildX

on:
  workflow_dispatch:
  schedule:
    - cron: '30 16 * * 5'

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  DOCKER_BUILD: buildImageX.sh
  DOCKER_IMAGE: summary/openwrt-aarch64
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Get openwrt version
      run: |
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd $GITHUB_WORKSPACE/openwrt
        version=$(echo "$(cat package/lean/default-settings/files/zzz-default-settings)" | grep -Po "DISTRIB_REVISION=\'\K[^\']*")
        echo "TAG=$version" >> $GITHUB_ENV

    - name: Get openwrt firmware
      run: |
        cd $GITHUB_WORKSPACE/docker
        wget -q $(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/releases | grep ROOTFS_PLUS.*rootfs.tar.gz | cut -d '"' -f 4)
        chmod +x $DOCKER_BUILD && ./$DOCKER_BUILD

    - name: Set up QEMU
      uses: docker/setup-qemu-action@master

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master

    - name: Login to Docker Hub
      uses: docker/login-action@master
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker
      uses: docker/build-push-action@master
      with:
        platforms: linux/arm64
        context: docker
        push: true
        tags: |
          ${{ env.DOCKER_IMAGE }}:${{ env.TAG }}
          ${{ env.DOCKER_IMAGE }}
